import type { Processo, TemaProcesso, DisponibilidadeServidor } from "@/lib/types/processo";

const servidores = [
  {
    id: "s1",
    nome: "João Silva",
    cargo: "servidor" as const,
    email: "joao.silva@carf.gov.br",
    turma: "Turma 1A",
    disponibilidade: "disponivel" as DisponibilidadeServidor,
    cargaAtual: 5,
    especialidades: ["IRPJ", "CSLL"] as TemaProcesso[],
  },
  {
    id: "s2",
    nome: "Maria Santos",
    cargo: "servidor" as const,
    email: "maria.santos@carf.gov.br",
    turma: "Turma 1B",
    disponibilidade: "moderado" as DisponibilidadeServidor,
    cargaAtual: 8,
    especialidades: ["IPI", "COFINS"] as TemaProcesso[],
  },
  {
    id: "s3",
    nome: "Pedro Oliveira",
    cargo: "servidor" as const,
    email: "pedro.oliveira@carf.gov.br",
    turma: "Turma 2A",
    disponibilidade: "sobrecarregado" as DisponibilidadeServidor,
    cargaAtual: 12,
    especialidades: ["IRPJ", "IPI"] as TemaProcesso[],
  },
  {
    id: "s4",
    nome: "Ana Costa",
    cargo: "servidor" as const,
    email: "ana.costa@carf.gov.br",
    turma: "Turma 2B",
    disponibilidade: "disponivel" as DisponibilidadeServidor,
    cargaAtual: 4,
    especialidades: ["ICMS", "ISS"] as TemaProcesso[],
  },
  {
    id: "s5",
    nome: "Carlos Mendes",
    cargo: "servidor" as const,
    email: "carlos.mendes@carf.gov.br",
    turma: "Turma 3A",
    disponibilidade: "moderado" as DisponibilidadeServidor,
    cargaAtual: 7,
    especialidades: ["PIS", "COFINS"] as TemaProcesso[],
  },
  {
    id: "s6",
    nome: "Juliana Lima",
    cargo: "servidor" as const,
    email: "juliana.lima@carf.gov.br",
    turma: "Turma 3B",
    disponibilidade: "disponivel" as DisponibilidadeServidor,
    cargaAtual: 6,
    especialidades: ["CSLL", "OUTROS"] as TemaProcesso[],
  },
  {
    id: "s7",
    nome: "Roberto Alves",
    cargo: "servidor" as const,
    email: "roberto.alves@carf.gov.br",
    turma: "Turma 1A",
    disponibilidade: "sobrecarregado" as DisponibilidadeServidor,
    cargaAtual: 11,
    especialidades: ["IRPJ", "COFINS"] as TemaProcesso[],
  },
  {
    id: "s8",
    nome: "Fernanda Dias",
    cargo: "servidor" as const,
    email: "fernanda.dias@carf.gov.br",
    turma: "Turma 2A",
    disponibilidade: "disponivel" as DisponibilidadeServidor,
    cargaAtual: 3,
    especialidades: ["IPI", "ICMS"] as TemaProcesso[],
  },
];

export const consultarProcessos: Processo[] = [
  {
    id: "c1",
    numeroProcesso: "10001.234/2024-01",
    descricaoResumida: "Recurso voluntário - compensação tributária IRPJ exercício 2020",
    status: "em_analise",
    prazos: [
      {
        tipo: "legal",
        dataLimite: new Date("2025-11-20"),
        diasRestantes: 33,
        status: "em_dia",
      },
    ],
    participantes: [servidores[0]],
    tempoEstimadoConclusao: 45,
    pecasSimilares: [],
    nivelComplexidade: 2,
    valorDisputa: 850000,
    numeroDocumentos: 32,
    criadoEm: new Date("2024-08-10"),
    atualizadoEm: new Date("2025-10-15"),
    setorResponsavel: "Setor de Análise Tributária",
    turma: "Turma 1A",
    tema: "IRPJ",
    situacao: "normal",
    tempoMedioTramitacao: 120,
    servidorAtual: servidores[0],
  },
  {
    id: "c2",
    numeroProcesso: "10002.567/2024-02",
    descricaoResumida: "Impugnação de multa qualificada - omissão de receitas IPI",
    status: "aguardando_manifestacao",
    prazos: [
      {
        tipo: "legal",
        dataLimite: new Date("2025-10-22"),
        diasRestantes: 4,
        status: "proximo_vencimento",
      },
    ],
    participantes: [servidores[1]],
    tempoEstimadoConclusao: 90,
    pecasSimilares: [],
    nivelComplexidade: 4,
    valorDisputa: 5600000,
    numeroDocumentos: 156,
    criadoEm: new Date("2024-07-05"),
    atualizadoEm: new Date("2025-10-17"),
    setorResponsavel: "Setor de Análise Tributária",
    turma: "Turma 1B",
    tema: "IPI",
    situacao: "atrasado",
    tempoMedioTramitacao: 180,
    servidorAtual: servidores[1],
  },
  {
    id: "c3",
    numeroProcesso: "10003.890/2024-03",
    descricaoResumida: "Consulta sobre aplicação de alíquota diferenciada - COFINS",
    status: "em_relatoria",
    prazos: [
      {
        tipo: "interno",
        dataLimite: new Date("2025-11-15"),
        diasRestantes: 28,
        status: "em_dia",
      },
    ],
    participantes: [servidores[2]],
    tempoEstimadoConclusao: 60,
    pecasSimilares: [],
    nivelComplexidade: 3,
    valorDisputa: 2300000,
    numeroDocumentos: 78,
    criadoEm: new Date("2024-09-12"),
    atualizadoEm: new Date("2025-10-16"),
    setorResponsavel: "Setor de Consultas",
    turma: "Turma 2A",
    tema: "COFINS",
    situacao: "normal",
    tempoMedioTramitacao: 90,
    servidorAtual: servidores[2],
  },
  {
    id: "c4",
    numeroProcesso: "10004.123/2025-04",
    descricaoResumida: "Revisão de auto de infração - ICMS operações interestaduais",
    status: "em_analise",
    prazos: [
      {
        tipo: "legal",
        dataLimite: new Date("2025-12-01"),
        diasRestantes: 44,
        status: "em_dia",
      },
    ],
    participantes: [servidores[3]],
    tempoEstimadoConclusao: 75,
    pecasSimilares: [],
    nivelComplexidade: 2,
    valorDisputa: 1200000,
    numeroDocumentos: 45,
    criadoEm: new Date("2025-09-01"),
    atualizadoEm: new Date("2025-10-14"),
    setorResponsavel: "Setor de Fiscalização",
    turma: "Turma 2B",
    tema: "ICMS",
    situacao: "normal",
    tempoMedioTramitacao: 100,
    servidorAtual: servidores[3],
  },
  {
    id: "c5",
    numeroProcesso: "10005.456/2024-05",
    descricaoResumida: "Recurso especial - tributação de serviços digitais ISS",
    status: "aguardando_manifestacao",
    prazos: [
      {
        tipo: "legal",
        dataLimite: new Date("2025-10-19"),
        diasRestantes: 1,
        status: "proximo_vencimento",
      },
    ],
    participantes: [servidores[4]],
    tempoEstimadoConclusao: 120,
    pecasSimilares: [],
    nivelComplexidade: 3,
    valorDisputa: 950000,
    numeroDocumentos: 92,
    criadoEm: new Date("2024-06-20"),
    atualizadoEm: new Date("2025-10-17"),
    setorResponsavel: "Setor de Análise Tributária",
    turma: "Turma 3A",
    tema: "ISS",
    situacao: "redistribuicao_sugerida",
    tempoMedioTramitacao: 150,
    servidorAtual: servidores[4],
  },
  {
    id: "c6",
    numeroProcesso: "10006.789/2024-06",
    descricaoResumida: "Discussão sobre base de cálculo - PIS regime não cumulativo",
    status: "em_analise",
    prazos: [
      {
        tipo: "interno",
        dataLimite: new Date("2025-11-25"),
        diasRestantes: 38,
        status: "em_dia",
      },
    ],
    participantes: [servidores[5]],
    tempoEstimadoConclusao: 55,
    pecasSimilares: [],
    nivelComplexidade: 2,
    valorDisputa: 3100000,
    numeroDocumentos: 67,
    criadoEm: new Date("2024-08-15"),
    atualizadoEm: new Date("2025-10-13"),
    setorResponsavel: "Setor de Análise Tributária",
    turma: "Turma 3B",
    tema: "PIS",
    situacao: "normal",
    tempoMedioTramitacao: 95,
    servidorAtual: servidores[5],
  },
  {
    id: "c7",
    numeroProcesso: "10007.012/2024-07",
    descricaoResumida: "Restituição de CSLL recolhida indevidamente - lucro presumido",
    status: "encerrado",
    prazos: [
      {
        tipo: "legal",
        dataLimite: new Date("2025-09-30"),
        diasRestantes: -18,
        status: "atrasado",
      },
    ],
    participantes: [servidores[6]],
    tempoEstimadoConclusao: 0,
    pecasSimilares: [],
    nivelComplexidade: 1,
    valorDisputa: 420000,
    numeroDocumentos: 18,
    criadoEm: new Date("2024-05-10"),
    atualizadoEm: new Date("2025-09-30"),
    setorResponsavel: "Setor de Restituições",
    turma: "Turma 1A",
    tema: "CSLL",
    situacao: "normal",
    tempoMedioTramitacao: 80,
    servidorAtual: servidores[6],
  },
  {
    id: "c8",
    numeroProcesso: "10008.345/2024-08",
    descricaoResumida: "Mandado de segurança - suspensão de exigibilidade tributária",
    status: "em_relatoria",
    prazos: [
      {
        tipo: "legal",
        dataLimite: new Date("2025-11-05"),
        diasRestantes: 18,
        status: "em_dia",
      },
    ],
    participantes: [servidores[7]],
    tempoEstimadoConclusao: 40,
    pecasSimilares: [],
    nivelComplexidade: 1,
    valorDisputa: 180000,
    numeroDocumentos: 12,
    criadoEm: new Date("2024-08-25"),
    atualizadoEm: new Date("2025-10-14"),
    setorResponsavel: "Setor Jurídico",
    turma: "Turma 2A",
    tema: "OUTROS",
    situacao: "normal",
    tempoMedioTramitacao: 70,
    servidorAtual: servidores[7],
  },
  {
    id: "c9",
    numeroProcesso: "10009.678/2024-09",
    descricaoResumida: "Recurso de ofício - glosa de créditos IRPJ período 2018-2020",
    status: "em_analise",
    prazos: [
      {
        tipo: "legal",
        dataLimite: new Date("2025-10-25"),
        diasRestantes: 7,
        status: "proximo_vencimento",
      },
    ],
    participantes: [servidores[0]],
    tempoEstimadoConclusao: 110,
    pecasSimilares: [],
    nivelComplexidade: 4,
    valorDisputa: 8900000,
    numeroDocumentos: 203,
    criadoEm: new Date("2024-06-01"),
    atualizadoEm: new Date("2025-10-16"),
    setorResponsavel: "Setor de Análise Tributária",
    turma: "Turma 1A",
    tema: "IRPJ",
    situacao: "aguardando_parecer_tecnico",
    tempoMedioTramitacao: 200,
    servidorAtual: servidores[0],
  },
  {
    id: "c10",
    numeroProcesso: "10010.901/2024-10",
    descricaoResumida: "Impugnação administrativa - IPI importação com drawback",
    status: "aguardando_manifestacao",
    prazos: [
      {
        tipo: "interno",
        dataLimite: new Date("2025-11-10"),
        diasRestantes: 23,
        status: "em_dia",
      },
    ],
    participantes: [servidores[1]],
    tempoEstimadoConclusao: 85,
    pecasSimilares: [],
    nivelComplexidade: 3,
    valorDisputa: 4500000,
    numeroDocumentos: 134,
    criadoEm: new Date("2024-07-18"),
    atualizadoEm: new Date("2025-10-15"),
    setorResponsavel: "Setor de Comércio Exterior",
    turma: "Turma 1B",
    tema: "IPI",
    situacao: "redistribuicao_sugerida",
    tempoMedioTramitacao: 160,
    servidorAtual: servidores[1],
  },
  {
    id: "c11",
    numeroProcesso: "10011.234/2025-11",
    descricaoResumida: "Consulta - aplicação de isenção COFINS exportação indireta",
    status: "em_analise",
    prazos: [
      {
        tipo: "legal",
        dataLimite: new Date("2025-12-15"),
        diasRestantes: 58,
        status: "em_dia",
      },
    ],
    participantes: [servidores[2]],
    tempoEstimadoConclusao: 50,
    pecasSimilares: [],
    nivelComplexidade: 2,
    valorDisputa: 1800000,
    numeroDocumentos: 54,
    criadoEm: new Date("2025-09-10"),
    atualizadoEm: new Date("2025-10-12"),
    setorResponsavel: "Setor de Consultas",
    turma: "Turma 2A",
    tema: "COFINS",
    situacao: "normal",
    tempoMedioTramitacao: 85,
    servidorAtual: servidores[2],
  },
  {
    id: "c12",
    numeroProcesso: "10012.567/2024-12",
    descricaoResumida: "Auto de infração - ICMS substituição tributária combustíveis",
    status: "em_relatoria",
    prazos: [
      {
        tipo: "legal",
        dataLimite: new Date("2025-11-08"),
        diasRestantes: 21,
        status: "em_dia",
      },
    ],
    participantes: [servidores[3]],
    tempoEstimadoConclusao: 95,
    pecasSimilares: [],
    nivelComplexidade: 3,
    valorDisputa: 6700000,
    numeroDocumentos: 187,
    criadoEm: new Date("2024-06-15"),
    atualizadoEm: new Date("2025-10-11"),
    setorResponsavel: "Setor de Fiscalização",
    turma: "Turma 2B",
    tema: "ICMS",
    situacao: "normal",
    tempoMedioTramitacao: 145,
    servidorAtual: servidores[3],
  },
  {
    id: "c13",
    numeroProcesso: "10013.890/2024-13",
    descricaoResumida: "Recurso administrativo - ISS construção civil subempreitada",
    status: "em_analise",
    prazos: [
      {
        tipo: "interno",
        dataLimite: new Date("2025-10-21"),
        diasRestantes: 3,
        status: "proximo_vencimento",
      },
    ],
    participantes: [servidores[4]],
    tempoEstimadoConclusao: 70,
    pecasSimilares: [],
    nivelComplexidade: 2,
    valorDisputa: 670000,
    numeroDocumentos: 41,
    criadoEm: new Date("2024-07-22"),
    atualizadoEm: new Date("2025-10-17"),
    setorResponsavel: "Setor de Análise Tributária",
    turma: "Turma 3A",
    tema: "ISS",
    situacao: "atrasado",
    tempoMedioTramitacao: 110,
    servidorAtual: servidores[4],
  },
  {
    id: "c14",
    numeroProcesso: "10014.123/2024-14",
    descricaoResumida: "Discussão sobre crédito presumido PIS - indústria farmacêutica",
    status: "aguardando_manifestacao",
    prazos: [
      {
        tipo: "legal",
        dataLimite: new Date("2025-11-30"),
        diasRestantes: 43,
        status: "em_dia",
      },
    ],
    participantes: [servidores[5]],
    tempoEstimadoConclusao: 100,
    pecasSimilares: [],
    nivelComplexidade: 4,
    valorDisputa: 12500000,
    numeroDocumentos: 289,
    criadoEm: new Date("2024-05-28"),
    atualizadoEm: new Date("2025-10-10"),
    setorResponsavel: "Setor de Análise Tributária",
    turma: "Turma 3B",
    tema: "PIS",
    situacao: "aguardando_parecer_tecnico",
    tempoMedioTramitacao: 190,
    servidorAtual: servidores[5],
  },
  {
    id: "c15",
    numeroProcesso: "10015.456/2024-15",
    descricaoResumida: "Recurso voluntário - base de cálculo CSLL prejuízo fiscal",
    status: "em_analise",
    prazos: [
      {
        tipo: "legal",
        dataLimite: new Date("2025-11-12"),
        diasRestantes: 25,
        status: "em_dia",
      },
    ],
    participantes: [servidores[6]],
    tempoEstimadoConclusao: 65,
    pecasSimilares: [],
    nivelComplexidade: 3,
    valorDisputa: 3400000,
    numeroDocumentos: 98,
    criadoEm: new Date("2024-08-05"),
    atualizadoEm: new Date("2025-10-09"),
    setorResponsavel: "Setor de Análise Tributária",
    turma: "Turma 1A",
    tema: "CSLL",
    situacao: "redistribuicao_sugerida",
    tempoMedioTramitacao: 125,
    servidorAtual: servidores[6],
  },
  {
    id: "c16",
    numeroProcesso: "10016.789/2025-16",
    descricaoResumida: "Impugnação - IRPJ lucro real controladas no exterior",
    status: "em_relatoria",
    prazos: [
      {
        tipo: "interno",
        dataLimite: new Date("2025-12-20"),
        diasRestantes: 63,
        status: "em_dia",
      },
    ],
    participantes: [servidores[7]],
    tempoEstimadoConclusao: 140,
    pecasSimilares: [],
    nivelComplexidade: 4,
    valorDisputa: 15800000,
    numeroDocumentos: 356,
    criadoEm: new Date("2025-08-01"),
    atualizadoEm: new Date("2025-10-08"),
    setorResponsavel: "Setor de Tributação Internacional",
    turma: "Turma 2A",
    tema: "IRPJ",
    situacao: "aguardando_parecer_tecnico",
    tempoMedioTramitacao: 220,
    servidorAtual: servidores[7],
  },
  {
    id: "c17",
    numeroProcesso: "10017.012/2024-17",
    descricaoResumida: "Consulta sobre IPI - produtos isentos regime especial",
    status: "em_analise",
    prazos: [
      {
        tipo: "legal",
        dataLimite: new Date("2025-10-28"),
        diasRestantes: 10,
        status: "proximo_vencimento",
      },
    ],
    participantes: [servidores[0]],
    tempoEstimadoConclusao: 45,
    pecasSimilares: [],
    nivelComplexidade: 1,
    valorDisputa: 520000,
    numeroDocumentos: 23,
    criadoEm: new Date("2024-09-05"),
    atualizadoEm: new Date("2025-10-16"),
    setorResponsavel: "Setor de Consultas",
    turma: "Turma 1A",
    tema: "IPI",
    situacao: "normal",
    tempoMedioTramitacao: 75,
    servidorAtual: servidores[0],
  },
  {
    id: "c18",
    numeroProcesso: "10018.345/2024-18",
    descricaoResumida: "Auto de infração - COFINS incidência monofásica",
    status: "aguardando_manifestacao",
    prazos: [
      {
        tipo: "legal",
        dataLimite: new Date("2025-11-18"),
        diasRestantes: 31,
        status: "em_dia",
      },
    ],
    participantes: [servidores[1]],
    tempoEstimadoConclusao: 80,
    pecasSimilares: [],
    nivelComplexidade: 3,
    valorDisputa: 5200000,
    numeroDocumentos: 143,
    criadoEm: new Date("2024-07-10"),
    atualizadoEm: new Date("2025-10-15"),
    setorResponsavel: "Setor de Fiscalização",
    turma: "Turma 1B",
    tema: "COFINS",
    situacao: "normal",
    tempoMedioTramitacao: 135,
    servidorAtual: servidores[1],
  },
  {
    id: "c19",
    numeroProcesso: "10019.678/2024-19",
    descricaoResumida: "Recurso especial - ICMS guerra fiscal benefícios fiscais",
    status: "em_analise",
    prazos: [
      {
        tipo: "interno",
        dataLimite: new Date("2025-10-24"),
        diasRestantes: 6,
        status: "proximo_vencimento",
      },
    ],
    participantes: [servidores[2]],
    tempoEstimadoConclusao: 105,
    pecasSimilares: [],
    nivelComplexidade: 4,
    valorDisputa: 9800000,
    numeroDocumentos: 267,
    criadoEm: new Date("2024-06-12"),
    atualizadoEm: new Date("2025-10-14"),
    setorResponsavel: "Setor de Análise Tributária",
    turma: "Turma 2A",
    tema: "ICMS",
    situacao: "redistribuicao_sugerida",
    tempoMedioTramitacao: 175,
    servidorAtual: servidores[2],
  },
  {
    id: "c20",
    numeroProcesso: "10020.901/2025-20",
    descricaoResumida: "Impugnação - ISS intermediação de negócios plataforma digital",
    status: "em_relatoria",
    prazos: [
      {
        tipo: "legal",
        dataLimite: new Date("2025-12-05"),
        diasRestantes: 48,
        status: "em_dia",
      },
    ],
    participantes: [servidores[3]],
    tempoEstimadoConclusao: 90,
    pecasSimilares: [],
    nivelComplexidade: 3,
    valorDisputa: 2900000,
    numeroDocumentos: 112,
    criadoEm: new Date("2025-08-20"),
    atualizadoEm: new Date("2025-10-13"),
    setorResponsavel: "Setor de Economia Digital",
    turma: "Turma 2B",
    tema: "ISS",
    situacao: "normal",
    tempoMedioTramitacao: 105,
    servidorAtual: servidores[3],
  },
  {
    id: "c21",
    numeroProcesso: "10021.234/2024-21",
    descricaoResumida: "Recurso administrativo - PIS regime cumulativo vs não cumulativo",
    status: "em_analise",
    prazos: [
      {
        tipo: "legal",
        dataLimite: new Date("2025-11-22"),
        diasRestantes: 35,
        status: "em_dia",
      },
    ],
    participantes: [servidores[4]],
    tempoEstimadoConclusao: 75,
    pecasSimilares: [],
    nivelComplexidade: 2,
    valorDisputa: 1950000,
    numeroDocumentos: 76,
    criadoEm: new Date("2024-08-12"),
    atualizadoEm: new Date("2025-10-12"),
    setorResponsavel: "Setor de Análise Tributária",
    turma: "Turma 3A",
    tema: "PIS",
    situacao: "normal",
    tempoMedioTramitacao: 115,
    servidorAtual: servidores[4],
  },
  {
    id: "c22",
    numeroProcesso: "10022.567/2024-22",
    descricaoResumida: "Consulta - CSLL adicional sociedades de grande porte",
    status: "aguardando_manifestacao",
    prazos: [
      {
        tipo: "interno",
        dataLimite: new Date("2025-10-26"),
        diasRestantes: 8,
        status: "proximo_vencimento",
      },
    ],
    participantes: [servidores[5]],
    tempoEstimadoConclusao: 60,
    pecasSimilares: [],
    nivelComplexidade: 2,
    valorDisputa: 780000,
    numeroDocumentos: 34,
    criadoEm: new Date("2024-09-08"),
    atualizadoEm: new Date("2025-10-11"),
    setorResponsavel: "Setor de Consultas",
    turma: "Turma 3B",
    tema: "CSLL",
    situacao: "normal",
    tempoMedioTramitacao: 80,
    servidorAtual: servidores[5],
  },
  {
    id: "c23",
    numeroProcesso: "10023.890/2024-23",
    descricaoResumida: "Recurso de ofício - IRPJ preço de transferência operações internacionais",
    status: "em_analise",
    prazos: [
      {
        tipo: "legal",
        dataLimite: new Date("2025-10-30"),
        diasRestantes: 12,
        status: "proximo_vencimento",
      },
    ],
    participantes: [servidores[6]],
    tempoEstimadoConclusao: 150,
    pecasSimilares: [],
    nivelComplexidade: 4,
    valorDisputa: 22300000,
    numeroDocumentos: 412,
    criadoEm: new Date("2024-05-15"),
    atualizadoEm: new Date("2025-10-10"),
    setorResponsavel: "Setor de Tributação Internacional",
    turma: "Turma 1A",
    tema: "IRPJ",
    situacao: "aguardando_parecer_tecnico",
    tempoMedioTramitacao: 240,
    servidorAtual: servidores[6],
  },
  {
    id: "c24",
    numeroProcesso: "10024.123/2025-24",
    descricaoResumida: "Impugnação administrativa - IPI equiparação a industrial",
    status: "em_relatoria",
    prazos: [
      {
        tipo: "legal",
        dataLimite: new Date("2025-12-10"),
        diasRestantes: 53,
        status: "em_dia",
      },
    ],
    participantes: [servidores[7]],
    tempoEstimadoConclusao: 70,
    pecasSimilares: [],
    nivelComplexidade: 2,
    valorDisputa: 1340000,
    numeroDocumentos: 58,
    criadoEm: new Date("2025-09-15"),
    atualizadoEm: new Date("2025-10-09"),
    setorResponsavel: "Setor de Análise Tributária",
    turma: "Turma 2A",
    tema: "IPI",
    situacao: "normal",
    tempoMedioTramitacao: 95,
    servidorAtual: servidores[7],
  },
  {
    id: "c25",
    numeroProcesso: "10025.456/2024-25",
    descricaoResumida: "Auto de infração - COFINS insumos crédito PIS/COFINS",
    status: "em_analise",
    prazos: [
      {
        tipo: "interno",
        dataLimite: new Date("2025-11-28"),
        diasRestantes: 41,
        status: "em_dia",
      },
    ],
    participantes: [servidores[0]],
    tempoEstimadoConclusao: 95,
    pecasSimilares: [],
    nivelComplexidade: 3,
    valorDisputa: 7200000,
    numeroDocumentos: 176,
    criadoEm: new Date("2024-07-01"),
    atualizadoEm: new Date("2025-10-17"),
    setorResponsavel: "Setor de Fiscalização",
    turma: "Turma 1A",
    tema: "COFINS",
    situacao: "redistribuicao_sugerida",
    tempoMedioTramitacao: 155,
    servidorAtual: servidores[0],
  },
];
